/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: ee6c62f6f972736e5fbcc597fff6f21c)
interface __BaseEnv_Env {
	DB: D1Database;
	LEAD_RATE_LIMITER: RateLimit;
	TURNSTILE_SITE_KEY: "0x4AAAAAAFJ99Z487LueFk3h";
	TURNSTILE_HOSTNAMES: "deal-intel-sa.ndominguez.workers.dev";
	MARKETCHECK_API_KEY: string;
	AUTODEV_API_KEY: string;
	ADMIN_TOKEN: string;
	CLICKUP_API_TOKEN: string;
	CLICKUP_LIST_ID: string;
	TURNSTILE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TURNSTILE_SITE_KEY" | "TURNSTILE_HOSTNAMES" | "MARKETCHECK_API_KEY" | "AUTODEV_API_KEY" | "ADMIN_TOKEN" | "CLICKUP_API_TOKEN" | "CLICKUP_LIST_ID" | "TURNSTILE_SECRET_KEY">> {}
}
