export const SEED_LISTINGS = [
  {
    external_id: "mc_001",
    vin: "3TMCZ5AN0LM364521",
    year: 2021,
    make: "Toyota",
    model: "Tacoma",
    trim: "TRD Off-Road",
    body_type: "Truck",
    price: 34500,
    mileage: 42000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78216",
    dealer_name: "North Park Toyota",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_001",
    title_status: "clean",
    image_urls: ["https://images.unsplash.com/photo-1629897048514-3dd7414cc710?w=800&q=80"]
  },
  {
    external_id: "mc_002",
    vin: "1FTEW1EP4NFA12345",
    year: 2022,
    make: "Ford",
    model: "F-150",
    trim: "XLT",
    body_type: "Truck",
    price: 39900,
    mileage: 35000,
    city: "New Braunfels",
    state: "TX",
    postal_code: "78130",
    dealer_name: "Bluebonnet Ford",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_002",
    title_status: "clean",
    image_urls: ["https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800&q=80"]
  },
  {
    external_id: "mc_003",
    vin: "1GNSKBKC8LR123456",
    year: 2020,
    make: "Chevrolet",
    model: "Tahoe",
    trim: "LT",
    body_type: "SUV",
    price: 42500,
    mileage: 68000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78209",
    dealer_name: null,
    is_dealer: false,
    listing_url: "https://example.com/listing/mc_003",
    title_status: "clean",
    image_urls: ["https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80"]
  },
  {
    external_id: "mc_004",
    vin: "19XFC2F59KE012345",
    year: 2019,
    make: "Honda",
    model: "Civic",
    trim: "EX",
    body_type: "Sedan",
    price: 18500,
    mileage: 55000,
    city: "Boerne",
    state: "TX",
    postal_code: "78006",
    dealer_name: "Boerne Honda",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_004",
    title_status: "clean",
    image_urls: ["https://images.unsplash.com/photo-1605810731057-048c26ab8eb9?w=800&q=80"]
  },
  {
    external_id: "mc_005",
    vin: "1C4HJXFG0MW123456",
    year: 2021,
    make: "Jeep",
    model: "Wrangler",
    trim: "Unlimited Rubicon",
    body_type: "SUV",
    price: 36000,
    mileage: 48000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78229",
    dealer_name: "Ancira Jeep",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_005",
    title_status: "clean",
    image_urls: ["https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800&q=80"]
  },
  {
    external_id: "mc_006",
    vin: "5TDJZRFH8HS123456",
    year: 2017,
    make: "Toyota",
    model: "Highlander",
    trim: "XLE",
    body_type: "SUV",
    price: 26500,
    mileage: 78000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78240",
    dealer_name: "Cavender Toyota",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_006",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_007",
    vin: "3GCPWDED1LG123456",
    year: 2020,
    make: "Chevrolet",
    model: "Silverado",
    trim: "LT Trail Boss",
    body_type: "Truck",
    price: 37800,
    mileage: 52000,
    city: "Seguin",
    state: "TX",
    postal_code: "78155",
    dealer_name: null,
    is_dealer: false,
    listing_url: "https://example.com/listing/mc_007",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_008",
    vin: "4T1B11HK8KU123456",
    year: 2019,
    make: "Toyota",
    model: "Camry",
    trim: "SE",
    body_type: "Sedan",
    price: 21200,
    mileage: 45000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78201",
    dealer_name: "North Park Toyota",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_008",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_009",
    vin: "1FM5K8D88LGA12345",
    year: 2020,
    make: "Ford",
    model: "Explorer",
    trim: "XLT",
    body_type: "SUV",
    price: 31500,
    mileage: 62000,
    city: "San Marcos",
    state: "TX",
    postal_code: "78666",
    dealer_name: null,
    is_dealer: false,
    listing_url: "https://example.com/listing/mc_009",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_010",
    vin: "1C6RR7KT8LS123456",
    year: 2020,
    make: "Ram",
    model: "1500",
    trim: "Big Horn",
    body_type: "Truck",
    price: 35900,
    mileage: 58000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78245",
    dealer_name: "IPAC Ram",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_010",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_011",
    vin: "JTEBU5JR5L5123456",
    year: 2020,
    make: "Toyota",
    model: "4Runner",
    trim: "SR5 Premium",
    body_type: "SUV",
    price: 37200,
    mileage: 44000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78258",
    dealer_name: "North Park Toyota",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_011",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_012",
    vin: "2HGFC2F51MH123456",
    year: 2021,
    make: "Honda",
    model: "Civic",
    trim: "Sport",
    body_type: "Sedan",
    price: 22800,
    mileage: 32000,
    city: "Schertz",
    state: "TX",
    postal_code: "78154",
    dealer_name: "Gunn Honda",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_012",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_013",
    vin: "3TMCZ5AN8MM123456",
    year: 2021,
    make: "Toyota",
    model: "Tacoma",
    trim: "SR5",
    body_type: "Truck",
    price: 31200,
    mileage: 38000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78232",
    dealer_name: null,
    is_dealer: false,
    listing_url: "https://example.com/listing/mc_013",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_014",
    vin: "1FTEW1EP7NKD12345",
    year: 2022,
    make: "Ford",
    model: "F-150",
    trim: "Lariat",
    body_type: "Truck",
    price: 48500,
    mileage: 28000,
    city: "New Braunfels",
    state: "TX",
    postal_code: "78130",
    dealer_name: "Bluebonnet Ford",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_014",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_015",
    vin: "3TMCZ5AN2LM987654",
    year: 2020,
    make: "Toyota",
    model: "Tacoma",
    trim: "TRD Sport",
    body_type: "Truck",
    price: 33400,
    mileage: 51000,
    city: "Helotes",
    state: "TX",
    postal_code: "78023",
    dealer_name: null,
    is_dealer: false,
    listing_url: "https://example.com/listing/mc_015",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_016",
    vin: "1FTFW1E50MFA12345",
    year: 2021,
    make: "Ford",
    model: "F-150",
    trim: "XLT",
    body_type: "Truck",
    price: 38200,
    mileage: 41000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78210",
    dealer_name: "Northside Ford",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_016",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_017",
    vin: "1GNSKBKC9MR123456",
    year: 2021,
    make: "Chevrolet",
    model: "Tahoe",
    trim: "RST",
    body_type: "SUV",
    price: 49900,
    mileage: 35000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78257",
    dealer_name: "Cavender Chevrolet",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_017",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_018",
    vin: "WBA5R1C52LA123456",
    year: 2020,
    make: "BMW",
    model: "3 Series",
    trim: "330i",
    body_type: "Sedan",
    price: 29500,
    mileage: 48000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78209",
    dealer_name: null,
    is_dealer: false,
    listing_url: "https://example.com/listing/mc_018",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_019",
    vin: "2C3CDXCT5LH123456",
    year: 2020,
    make: "Dodge",
    model: "Charger",
    trim: "R/T",
    body_type: "Sedan",
    price: 28900,
    mileage: 52000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78221",
    dealer_name: "IPAC Dodge",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_019",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_020",
    vin: "5YFBURHE0LP123456",
    year: 2020,
    make: "Toyota",
    model: "Corolla",
    trim: "LE",
    body_type: "Sedan",
    price: 17900,
    mileage: 48000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78228",
    dealer_name: null,
    is_dealer: false,
    listing_url: "https://example.com/listing/mc_020",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_021",
    vin: "3GCPWDED5MG654321",
    year: 2021,
    make: "Chevrolet",
    model: "Silverado",
    trim: "Custom",
    body_type: "Truck",
    price: 34200,
    mileage: 44000,
    city: "Cibolo",
    state: "TX",
    postal_code: "78108",
    dealer_name: null,
    is_dealer: false,
    listing_url: "https://example.com/listing/mc_021",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_022",
    vin: "1C6RR7LT0MS654321",
    year: 2021,
    make: "Ram",
    model: "1500",
    trim: "Laramie",
    body_type: "Truck",
    price: 42500,
    mileage: 36000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78250",
    dealer_name: "IPAC Ram",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_022",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_023",
    vin: "JTEBU5JR8M5654321",
    year: 2021,
    make: "Toyota",
    model: "4Runner",
    trim: "TRD Off-Road",
    body_type: "SUV",
    price: 41500,
    mileage: 32000,
    city: "Boerne",
    state: "TX",
    postal_code: "78006",
    dealer_name: "Boerne Toyota",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_023",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_024",
    vin: "5TDKZ3DC5LS654321",
    year: 2020,
    make: "Toyota",
    model: "Highlander",
    trim: "LE",
    body_type: "SUV",
    price: 28900,
    mileage: 62000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78216",
    dealer_name: null,
    is_dealer: false,
    listing_url: "https://example.com/listing/mc_024",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_025",
    vin: "1HGCV1F39LA654321",
    year: 2020,
    make: "Honda",
    model: "Accord",
    trim: "Sport",
    body_type: "Sedan",
    price: 24200,
    mileage: 42000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78247",
    dealer_name: "Gunn Honda",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_025",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_026",
    vin: "1N4BL4DV8LC654321",
    year: 2020,
    make: "Nissan",
    model: "Altima",
    trim: "SR",
    body_type: "Sedan",
    price: 19800,
    mileage: 55000,
    city: "Live Oak",
    state: "TX",
    postal_code: "78233",
    dealer_name: null,
    is_dealer: false,
    listing_url: "https://example.com/listing/mc_026",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_027",
    vin: "3TMCZ5AN4MM654321",
    year: 2021,
    make: "Toyota",
    model: "Tacoma",
    trim: "TRD Off-Road",
    body_type: "Truck",
    price: 36800,
    mileage: 35000,
    city: "Kyle",
    state: "TX",
    postal_code: "78640",
    dealer_name: "Kyle Toyota",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_027",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_028",
    vin: "1FTEW1EP2NKE54321",
    year: 2022,
    make: "Ford",
    model: "F-150",
    trim: "XLT",
    body_type: "Truck",
    price: 41200,
    mileage: 30000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78223",
    dealer_name: "Northside Ford",
    is_dealer: true,
    listing_url: "https://example.com/listing/mc_028",
    title_status: "clean",
    image_urls: []
  },
  {
    external_id: "mc_029",
    vin: "SALVAGE1234567890",
    year: 2019,
    make: "Toyota",
    model: "Camry",
    trim: "LE",
    body_type: "Sedan",
    price: 14500,
    mileage: 72000,
    city: "San Antonio",
    state: "TX",
    postal_code: "78207",
    dealer_name: null,
    is_dealer: false,
    listing_url: "https://example.com/listing/mc_029",
    title_status: "salvage",
    image_urls: []
  },
  {
    external_id: "mc_030",
    vin: "1GCUYDED3LZ654321",
    year: 2020,
    make: "Chevrolet",
    model: "Silverado",
    trim: "RST",
    body_type: "Truck",
    price: 36500,
    mileage: 48000,
    city: "Pleasanton",
    state: "TX",
    postal_code: "78064",
    dealer_name: null,
    is_dealer: false,
    listing_url: "https://example.com/listing/mc_030",
    title_status: "clean",
    image_urls: []
  }
];
